[package]
name = "app"
version = "0.1.0"
description = "Lost Ark DPS Meter written in Rust"
authors = ["Snow"]
license = "GNU General Public License v3.0"
repository = "https://github.com/snoww/loa-logs"
default-run = "app"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
anyhow = "1.0.71"
chrono = { version = "0.4.24", features = ["serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.3.0", features = [ "http-all", "clipboard-all", "fs-copy-file", "fs-read-file", "global-shortcut-all", "path-all", "process-command-api", "process-relaunch", "protocol-asset", "shell-open", "system-tray", "updater", "window-hide", "window-maximize", "window-minimize", "window-set-always-on-top", "window-set-focus", "window-set-ignore-cursor-events", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
lazy_static = "1.4.0"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
bitflags = "2.2.1"
window-vibrancy = "0.3.2"
hashbrown = { version = "0.13.2", features = ["serde"] }
rusqlite = { version = "0.29.0", features = ["bundled", "serde_json"] }
tokio = { version = "1.28.1", features = ["rt", "macros"] }
serde_with = "2.3.3"
meter-core = { path = "Z:\\RustProjects\\meter-core-rs" }
log = "0.4.18"
flexi_logger = { version = "0.25", default-features = false }
zip = "0.6.6"


[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols
